#!/bin/bash

# first argument as the target domain

domain=$1

#colors

RED="\033[1;31m"
RESET="\033[0m"

# directories

base_dir="$domain"
info_path="$base_dir/info"
subdomain_path="$base_dir/subdomains"
screenshot_path="$base_dir/screenshots"

# create directories if they dont exist

for path in "$info_path" "$subdomain_path" "$screenshot_path"; do
        if  [ ! -d  "$path" ]; then
                mkdir -p "$path"
                echo "Diretorio criado: $path"
        fi
done

echo -e "${RED} [+] Iniciando pesquisa... ${RESET}"
whois "$domain" > "$info_path/whois.txt"

echo -e "${RED} [+] Rodando subfinder no alvo... ${RESET}"
subfinder -d "$domain" > "$subdomain_path/found.txt"

echo -e "${RED} [+] Rodando assetfinder no alvo... ${RESET}"
assetfinder "$domain" | grep "$domain" >> "$subdomain_path/found.txt"

echo -e "${RED} [+] Verificando dominios ativos... ${RESET}"
cat "$subdomain_path/found.txt" | grep "$domain" | sort -u | httprobe -prefer-https | grep https | sed 's/https\?:\/\///' | tee -a "$subdomain_path/alive.txt"

echo -e "${RED} [+] Fazendo capturas de tela... ${RESET}"
gowitness scan file -f "$subdomain_path/alive.txt" --screenshot-path "$screenshot_path" --no-http --write-jsonl
